version: '2.1'
services:
  dev:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    environment:
      - DB_NAME=mongodb://mongo:27017/coffee
      - PORT=1337
      - BOT_TOKEN=$BOT_TOKEN
      - MAX_BEANS=3
    ports:
      - "1337:1337"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27018:27017"
